# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget CapnProto::kj CapnProto::kj-test CapnProto::kj-async CapnProto::kj-http CapnProto::kj-gzip CapnProto::capnp CapnProto::capnp-rpc CapnProto::capnp-json CapnProto::capnpc CapnProto::capnp_tool CapnProto::capnpc_cpp CapnProto::capnpc_capnp)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target CapnProto::kj
add_library(CapnProto::kj STATIC IMPORTED)

set_target_properties(CapnProto::kj PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_generic_lambdas"
  INTERFACE_INCLUDE_DIRECTORIES "D:/capnproto/c++/src/kj/.."
)

# Create imported target CapnProto::kj-test
add_library(CapnProto::kj-test STATIC IMPORTED)

set_target_properties(CapnProto::kj-test PROPERTIES
  INTERFACE_LINK_LIBRARIES "CapnProto::kj"
)

# Create imported target CapnProto::kj-async
add_library(CapnProto::kj-async STATIC IMPORTED)

set_target_properties(CapnProto::kj-async PROPERTIES
  INTERFACE_LINK_LIBRARIES "CapnProto::kj;ws2_32"
)

# Create imported target CapnProto::kj-http
add_library(CapnProto::kj-http STATIC IMPORTED)

set_target_properties(CapnProto::kj-http PROPERTIES
  INTERFACE_LINK_LIBRARIES "CapnProto::kj-async;CapnProto::kj"
)

# Create imported target CapnProto::kj-gzip
add_library(CapnProto::kj-gzip STATIC IMPORTED)

# Create imported target CapnProto::capnp
add_library(CapnProto::capnp STATIC IMPORTED)

set_target_properties(CapnProto::capnp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/capnproto/c++/src/capnp/.."
  INTERFACE_LINK_LIBRARIES "CapnProto::kj"
)

# Create imported target CapnProto::capnp-rpc
add_library(CapnProto::capnp-rpc STATIC IMPORTED)

set_target_properties(CapnProto::capnp-rpc PROPERTIES
  INTERFACE_LINK_LIBRARIES "CapnProto::capnp;CapnProto::kj-async;CapnProto::kj"
)

# Create imported target CapnProto::capnp-json
add_library(CapnProto::capnp-json STATIC IMPORTED)

set_target_properties(CapnProto::capnp-json PROPERTIES
  INTERFACE_LINK_LIBRARIES "CapnProto::capnp;CapnProto::kj-async;CapnProto::kj"
)

# Create imported target CapnProto::capnpc
add_library(CapnProto::capnpc STATIC IMPORTED)

set_target_properties(CapnProto::capnpc PROPERTIES
  INTERFACE_LINK_LIBRARIES "CapnProto::capnp;CapnProto::kj"
)

# Create imported target CapnProto::capnp_tool
add_executable(CapnProto::capnp_tool IMPORTED)

# Create imported target CapnProto::capnpc_cpp
add_executable(CapnProto::capnpc_cpp IMPORTED)

# Create imported target CapnProto::capnpc_capnp
add_executable(CapnProto::capnpc_capnp IMPORTED)

# Import target "CapnProto::kj" for configuration "Debug"
set_property(TARGET CapnProto::kj APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::kj PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/kj/Debug/kj.lib"
  )

# Import target "CapnProto::kj-test" for configuration "Debug"
set_property(TARGET CapnProto::kj-test APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::kj-test PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/kj/Debug/kj-test.lib"
  )

# Import target "CapnProto::kj-async" for configuration "Debug"
set_property(TARGET CapnProto::kj-async APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::kj-async PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/kj/Debug/kj-async.lib"
  )

# Import target "CapnProto::kj-http" for configuration "Debug"
set_property(TARGET CapnProto::kj-http APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::kj-http PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/kj/Debug/kj-http.lib"
  )

# Import target "CapnProto::kj-gzip" for configuration "Debug"
set_property(TARGET CapnProto::kj-gzip APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::kj-gzip PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/kj/Debug/kj-gzip.lib"
  )

# Import target "CapnProto::capnp" for configuration "Debug"
set_property(TARGET CapnProto::capnp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::capnp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/capnp/Debug/capnp.lib"
  )

# Import target "CapnProto::capnp-rpc" for configuration "Debug"
set_property(TARGET CapnProto::capnp-rpc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::capnp-rpc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/capnp/Debug/capnp-rpc.lib"
  )

# Import target "CapnProto::capnp-json" for configuration "Debug"
set_property(TARGET CapnProto::capnp-json APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::capnp-json PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/capnp/Debug/capnp-json.lib"
  )

# Import target "CapnProto::capnpc" for configuration "Debug"
set_property(TARGET CapnProto::capnpc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::capnpc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/capnp/Debug/capnpc.lib"
  )

# Import target "CapnProto::capnp_tool" for configuration "Debug"
set_property(TARGET CapnProto::capnp_tool APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::capnp_tool PROPERTIES
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/capnp/Debug/capnp.exe"
  )

# Import target "CapnProto::capnpc_cpp" for configuration "Debug"
set_property(TARGET CapnProto::capnpc_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::capnpc_cpp PROPERTIES
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/capnp/Debug/capnpc-c++.exe"
  )

# Import target "CapnProto::capnpc_capnp" for configuration "Debug"
set_property(TARGET CapnProto::capnpc_capnp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(CapnProto::capnpc_capnp PROPERTIES
  IMPORTED_LOCATION_DEBUG "D:/capnproto/proj/src/capnp/Debug/capnpc-capnp.exe"
  )

# Import target "CapnProto::kj" for configuration "Release"
set_property(TARGET CapnProto::kj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::kj PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/kj/Release/kj.lib"
  )

# Import target "CapnProto::kj-test" for configuration "Release"
set_property(TARGET CapnProto::kj-test APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::kj-test PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/kj/Release/kj-test.lib"
  )

# Import target "CapnProto::kj-async" for configuration "Release"
set_property(TARGET CapnProto::kj-async APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::kj-async PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/kj/Release/kj-async.lib"
  )

# Import target "CapnProto::kj-http" for configuration "Release"
set_property(TARGET CapnProto::kj-http APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::kj-http PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/kj/Release/kj-http.lib"
  )

# Import target "CapnProto::kj-gzip" for configuration "Release"
set_property(TARGET CapnProto::kj-gzip APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::kj-gzip PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/kj/Release/kj-gzip.lib"
  )

# Import target "CapnProto::capnp" for configuration "Release"
set_property(TARGET CapnProto::capnp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::capnp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/capnp/Release/capnp.lib"
  )

# Import target "CapnProto::capnp-rpc" for configuration "Release"
set_property(TARGET CapnProto::capnp-rpc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::capnp-rpc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/capnp/Release/capnp-rpc.lib"
  )

# Import target "CapnProto::capnp-json" for configuration "Release"
set_property(TARGET CapnProto::capnp-json APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::capnp-json PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/capnp/Release/capnp-json.lib"
  )

# Import target "CapnProto::capnpc" for configuration "Release"
set_property(TARGET CapnProto::capnpc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::capnpc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/capnp/Release/capnpc.lib"
  )

# Import target "CapnProto::capnp_tool" for configuration "Release"
set_property(TARGET CapnProto::capnp_tool APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::capnp_tool PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/capnp/Release/capnp.exe"
  )

# Import target "CapnProto::capnpc_cpp" for configuration "Release"
set_property(TARGET CapnProto::capnpc_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::capnpc_cpp PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/capnp/Release/capnpc-c++.exe"
  )

# Import target "CapnProto::capnpc_capnp" for configuration "Release"
set_property(TARGET CapnProto::capnpc_capnp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(CapnProto::capnpc_capnp PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/capnproto/proj/src/capnp/Release/capnpc-capnp.exe"
  )

# Import target "CapnProto::kj" for configuration "MinSizeRel"
set_property(TARGET CapnProto::kj APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::kj PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/kj/MinSizeRel/kj.lib"
  )

# Import target "CapnProto::kj-test" for configuration "MinSizeRel"
set_property(TARGET CapnProto::kj-test APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::kj-test PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/kj/MinSizeRel/kj-test.lib"
  )

# Import target "CapnProto::kj-async" for configuration "MinSizeRel"
set_property(TARGET CapnProto::kj-async APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::kj-async PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/kj/MinSizeRel/kj-async.lib"
  )

# Import target "CapnProto::kj-http" for configuration "MinSizeRel"
set_property(TARGET CapnProto::kj-http APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::kj-http PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/kj/MinSizeRel/kj-http.lib"
  )

# Import target "CapnProto::kj-gzip" for configuration "MinSizeRel"
set_property(TARGET CapnProto::kj-gzip APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::kj-gzip PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/kj/MinSizeRel/kj-gzip.lib"
  )

# Import target "CapnProto::capnp" for configuration "MinSizeRel"
set_property(TARGET CapnProto::capnp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::capnp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/capnp/MinSizeRel/capnp.lib"
  )

# Import target "CapnProto::capnp-rpc" for configuration "MinSizeRel"
set_property(TARGET CapnProto::capnp-rpc APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::capnp-rpc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/capnp/MinSizeRel/capnp-rpc.lib"
  )

# Import target "CapnProto::capnp-json" for configuration "MinSizeRel"
set_property(TARGET CapnProto::capnp-json APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::capnp-json PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/capnp/MinSizeRel/capnp-json.lib"
  )

# Import target "CapnProto::capnpc" for configuration "MinSizeRel"
set_property(TARGET CapnProto::capnpc APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::capnpc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/capnp/MinSizeRel/capnpc.lib"
  )

# Import target "CapnProto::capnp_tool" for configuration "MinSizeRel"
set_property(TARGET CapnProto::capnp_tool APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::capnp_tool PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/capnp/MinSizeRel/capnp.exe"
  )

# Import target "CapnProto::capnpc_cpp" for configuration "MinSizeRel"
set_property(TARGET CapnProto::capnpc_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::capnpc_cpp PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/capnp/MinSizeRel/capnpc-c++.exe"
  )

# Import target "CapnProto::capnpc_capnp" for configuration "MinSizeRel"
set_property(TARGET CapnProto::capnpc_capnp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(CapnProto::capnpc_capnp PROPERTIES
  IMPORTED_LOCATION_MINSIZEREL "D:/capnproto/proj/src/capnp/MinSizeRel/capnpc-capnp.exe"
  )

# Import target "CapnProto::kj" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::kj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::kj PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/kj/RelWithDebInfo/kj.lib"
  )

# Import target "CapnProto::kj-test" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::kj-test APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::kj-test PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/kj/RelWithDebInfo/kj-test.lib"
  )

# Import target "CapnProto::kj-async" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::kj-async APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::kj-async PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/kj/RelWithDebInfo/kj-async.lib"
  )

# Import target "CapnProto::kj-http" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::kj-http APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::kj-http PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/kj/RelWithDebInfo/kj-http.lib"
  )

# Import target "CapnProto::kj-gzip" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::kj-gzip APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::kj-gzip PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/kj/RelWithDebInfo/kj-gzip.lib"
  )

# Import target "CapnProto::capnp" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::capnp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::capnp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnp.lib"
  )

# Import target "CapnProto::capnp-rpc" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::capnp-rpc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::capnp-rpc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnp-rpc.lib"
  )

# Import target "CapnProto::capnp-json" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::capnp-json APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::capnp-json PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnp-json.lib"
  )

# Import target "CapnProto::capnpc" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::capnpc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::capnpc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnpc.lib"
  )

# Import target "CapnProto::capnp_tool" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::capnp_tool APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::capnp_tool PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnp.exe"
  )

# Import target "CapnProto::capnpc_cpp" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::capnpc_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::capnpc_cpp PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnpc-c++.exe"
  )

# Import target "CapnProto::capnpc_capnp" for configuration "RelWithDebInfo"
set_property(TARGET CapnProto::capnpc_capnp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(CapnProto::capnpc_capnp PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnpc-capnp.exe"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
