# CMake generated Testfile for 
# Source directory: D:/capnproto/c++/src/capnp
# Build directory: D:/capnproto/proj/src/capnp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(capnp-tests-run "D:/capnproto/proj/src/capnp/Debug/capnp-tests.exe")
  set_tests_properties(capnp-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;246;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(capnp-tests-run "D:/capnproto/proj/src/capnp/Release/capnp-tests.exe")
  set_tests_properties(capnp-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;246;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(capnp-tests-run "D:/capnproto/proj/src/capnp/MinSizeRel/capnp-tests.exe")
  set_tests_properties(capnp-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;246;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(capnp-tests-run "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnp-tests.exe")
  set_tests_properties(capnp-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;246;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
else()
  add_test(capnp-tests-run NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(capnp-heavy-tests-run "D:/capnproto/proj/src/capnp/Debug/capnp-heavy-tests.exe")
  set_tests_properties(capnp-heavy-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;279;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(capnp-heavy-tests-run "D:/capnproto/proj/src/capnp/Release/capnp-heavy-tests.exe")
  set_tests_properties(capnp-heavy-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;279;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(capnp-heavy-tests-run "D:/capnproto/proj/src/capnp/MinSizeRel/capnp-heavy-tests.exe")
  set_tests_properties(capnp-heavy-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;279;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(capnp-heavy-tests-run "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnp-heavy-tests.exe")
  set_tests_properties(capnp-heavy-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;279;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
else()
  add_test(capnp-heavy-tests-run NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(capnp-evolution-tests-run "D:/capnproto/proj/src/capnp/Debug/capnp-evolution-tests.exe")
  set_tests_properties(capnp-evolution-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;284;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(capnp-evolution-tests-run "D:/capnproto/proj/src/capnp/Release/capnp-evolution-tests.exe")
  set_tests_properties(capnp-evolution-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;284;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(capnp-evolution-tests-run "D:/capnproto/proj/src/capnp/MinSizeRel/capnp-evolution-tests.exe")
  set_tests_properties(capnp-evolution-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;284;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(capnp-evolution-tests-run "D:/capnproto/proj/src/capnp/RelWithDebInfo/capnp-evolution-tests.exe")
  set_tests_properties(capnp-evolution-tests-run PROPERTIES  _BACKTRACE_TRIPLES "D:/capnproto/c++/src/capnp/CMakeLists.txt;284;add_test;D:/capnproto/c++/src/capnp/CMakeLists.txt;0;")
else()
  add_test(capnp-evolution-tests-run NOT_AVAILABLE)
endif()
